title: Atelic TSD Status
buildFuture: true
defaultContentLanguage: en
languageCode: en
baseURL: https://status.atelic.com
theme: cstate
preserveTaxonomyNames: true
taxonomies:
  affected: affected
outputs:
  page:
    - html
    - json
  section:
    - html
    - json
    - rss
  home:
    - html
    - json
    - rss
    - svg
  term:
    - html
    - json
    - rss
    - svg
outputFormats:
  svg:
    isPlainText: true
    mediaType: image/svg+xml
enableGitInfo: true
params:
  skipSeconds: false
  useRelativeTime: false
  disableDarkMode: false
  shortDateFormat: 15:04 UTC — Jan 2
  down: "#e60000"
  systems:
    - name: 1Password
      category: Cloud Services
    - name: Adobe
      category: Cloud Services
    - name: Box
      category: Cloud Services
    - name: CodeTwo
      category: Cloud Services
    - name: Duo
      category: Cloud Services
    - name: FortiGate
      category: Cloud Services
      description: FortiNet FortiGate Cloud management portal
    - name: Meraki
      category: Cloud Services
      description: Cisco Meraki cloud management portal
    - name: Microsoft
      category: Cloud Services
      description: Microsoft 365 desktop, mobile, and web apps
    - name: ScreenConnect
      category: Cloud Services
      description: ConnectWise ScreenConnect client application and technician portal
    - name: Zoom
      category: Cloud Services
    - name: 180E
      category: On Premise Services
      description: Core infrastructure located in Chicago at 180E
    - name: "204"
      category: On Premise Services
      description: Core infrastructure located in Indian Wells at Vintage 204
    - name: "302"
      category: On Premise Services
      description: Core infrastructure located in Indian Wells at Vintage 302
    - name: 30N
      category: On Premise Services
      description: Core infrastructure located in Chicago at 30N
    - name: 53W53
      category: On Premise Services
      description: Core infrastructure located in New York at 53W53
    - name: 65E
      category: On Premise Services
      description: Core infrastructure located in Chicago at 65E
    - name: Moore
      category: On Premise Services
      description: Core infrastructure located in Aspen at the Moore House
    - name: Tiehack
      category: On Premise Services
      description: Core infrastructure located in Aspen at Tiehack
    - name: Studio
      category: On Premise Services
      description: Core infrastructure located in Palm Desert at the El Paseo studio
  dateFormat: January 2, 2006 at 3:04 PM UTC
  brand: "#0a0c0f"
  enableLastMod: true
  headerTextColor: white
  logo: /img/cstate.png
  incidentPostsPerPage: 10
  googleAnalytics: UA-00000000-1
  customTabs: []
  alwaysKeepBrandColor: true
  disableComplexCalculations: false
  useLogo: true
  disrupted: "#cc4400"
  notice: "#24478f"
  incidentHistoryFormat: monthly
  disableIncidentHistory: false
  ok: "#008000"
  categories:
    - name: Cloud Services
      closed: false
      untitled: false
    - name: On Premise Services
      closed: false
  description: We continuously monitor the status of our services and if there are
    any interruptions, a note will be posted here.
  enableCustomHTML: true
  useLargeHeaderDesign: false
