title: Atelic Technology Services Department | Status
buildFuture: true
defaultContentLanguage: en
languageCode: en
baseURL: https://status.atelic.com
theme: cstate
preserveTaxonomyNames: true
taxonomies:
  affected: affected
outputs:
  page:
    - html
    - json
  section:
    - html
    - json
    - rss
  home:
    - html
    - json
    - rss
    - svg
  term:
    - html
    - json
    - rss
    - svg
outputFormats:
  svg:
    isPlainText: true
    mediaType: image/svg+xml
enableGitInfo: true
params:
  skipSeconds: false
  useRelativeTime: true
  disableDarkMode: false
  shortDateFormat: 15:04 UTC — Jan 2
  down: "#e60000"
  systems:
    - name: 1Password
      category: Cloud Services
    - name: Adobe
      category: Cloud Services
    - name: Cisco Meraki
      category: Cloud Services
    - name: FortiGate Cloud
      category: Cloud Services
  dateFormat: January 2, 2006 at 3:04 PM UTC
  brand: "#0a0c0f"
  enableLastMod: true
  headerTextColor: white
  logo: logo.png
  incidentPostsPerPage: 10
  googleAnalytics: UA-00000000-1
  customTabs: []
  alwaysKeepBrandColor: true
  disableComplexCalculations: false
  useLogo: true
  disrupted: "#cc4400"
  notice: "#24478f"
  incidentHistoryFormat: yearly
  disableIncidentHistory: false
  ok: "#008000"
  categories:
    - name: Cloud Services
      closed: true
      untitled: false
    - name: On Premise Services
      closed: true
  description: We continuously monitor the status of our services and if there are
    any interruptions, a note will be posted here.
  enableCustomHTML: true
  useLargeHeaderDesign: false
